language: generic
sudo: required
services:
  - docker

bevore_install:
  - docker build -t spaetzle/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true spaetzle/docker-react npm run test
